name: HTML

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install wheel
      run: pip install wheel
    - name: Install pyLODE
      run: pip install pylode
    - name: Build HTML
      run: mkdir -p public && pylode -i agrif.ttl -o public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
